/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Emity: typeof import('./src/components/Emity.vue')['default']
    GiftItem: typeof import('./src/components/GiftItem.vue')['default']
    Marquee: typeof import('./src/components/Marquee.vue')['default']
    MHeader: typeof import('./src/components/MHeader.vue')['default']
    Mobile: typeof import('./src/components/Mobile.vue')['default']
    Password: typeof import('./src/components/Password.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TheConfirmDialog: typeof import('./src/components/TheConfirmDialog.vue')['default']
    TheTimeRange: typeof import('./src/components/TheTimeRange.vue')['default']
    UploadImage: typeof import('./src/components/UploadImage.vue')['default']
  }
}
